export const FETCH_LATEST_RECIPES = 'FETCH_LATEST_RECIPES';
export const FETCH_MOST_LIKED_RECIPES = 'FETCH_MOST_LIKED_RECIPES';
export const FETCH_USER_RECIPES = 'FETCH_USER_RECIPES';
export const FETCH_USER_FAV_RECIPES = 'FETCH_USER_FAV_RECIPES';
export const FETCH_RECIPE_LIKES = 'FETCH_RECIPE_LIKES';